package dbus

import "github.com/godbus/dbus"

const (
	Connected          dbus.ObjectPath = "/Connected"
	CustomName         dbus.ObjectPath = "/CustomName"
	DeviceInstance     dbus.ObjectPath = "/DeviceInstance"
	DeviceType         dbus.ObjectPath = "/DeviceType"
	ErrorCode          dbus.ObjectPath = "/ErrorCode"
	FirmwareVersion    dbus.ObjectPath = "/FirmwareVersion"
	MgmtConnection     dbus.ObjectPath = "/Mgmt/Connection"
	MgmtProcessName    dbus.ObjectPath = "/Mgmt/ProcessName"
	MgmtProcessVersion dbus.ObjectPath = "/Mgmt/ProcessVersion"
	Position           dbus.ObjectPath = "/Position"
	ProductId          dbus.ObjectPath = "/ProductId"
	ProductName        dbus.ObjectPath = "/ProductName"
	Serial             dbus.ObjectPath = "/Serial"
	AcPower            dbus.ObjectPath = "/Ac/Power"
	AcL1Power          dbus.ObjectPath = "/Ac/L1/Power"
	AcL2Power          dbus.ObjectPath = "/Ac/L2/Power"
	AcL3Power          dbus.ObjectPath = "/Ac/L3/Power"
	AcL1Voltage        dbus.ObjectPath = "/Ac/L1/Voltage"
	AcL2Voltage        dbus.ObjectPath = "/Ac/L2/Voltage"
	AcL3Voltage        dbus.ObjectPath = "/Ac/L3/Voltage"
	AcL1Current        dbus.ObjectPath = "/Ac/L1/Current"
	AcL2Current        dbus.ObjectPath = "/Ac/L2/Current"
	AcL3Current        dbus.ObjectPath = "/Ac/L3/Current"
	AcEnergyForward    dbus.ObjectPath = "/Ac/Energy/Forward"
	AcL1EnergyForward  dbus.ObjectPath = "/Ac/L1/Energy/Forward"
	AcL2EnergyForward  dbus.ObjectPath = "/Ac/L2/Energy/Forward"
	AcL3EnergyForward  dbus.ObjectPath = "/Ac/L3/Energy/Forward"
	AcEnergyReverse    dbus.ObjectPath = "/Ac/Energy/Reverse"
	AcL1EnergyReverse  dbus.ObjectPath = "/Ac/L1/Energy/Reverse"
	AcL2EnergyReverse  dbus.ObjectPath = "/Ac/L2/Energy/Reverse"
	AcL3EnergyReverse  dbus.ObjectPath = "/Ac/L3/Energy/Reverse"
)
